highlight currently selected part on menu
sigmabeta/vgls-android pull request #67
Opened 2022-05-10 17:17 UTC by mezzocarattere

2022-05-10 20:04 UTC, sigmabeta requested changes
Just one very minor change, please.

2022-05-10 20:04 UTC, sigmabeta commented on core/ui-components/src/main/java/com/vgleadsheets/components/BindingAdapters.kt
> +    view: MaterialTextView,
Can we use the word "highlight" here instead of selected?

2022-05-10 20:26 UTC, mezzocarattere commented on core/ui-components/src/main/java/com/vgleadsheets/components/BindingAdapters.kt
> +    view: MaterialTextView,
Fixed

2022-05-11 01:28 UTC, sigmabeta approved these changes

2022-05-11 01:28 UTC, merged